### ISSUE TITLE
怎么在viewmodle里面显示toast呢

### ISSUE THREAD

**Issue by wppcc** [liuaries/android_mall#1]
用state定义的值设置了，是不会清除的，怎么在viewmodle里面显示toast呢

**Comment by liuaries** [comment]
不建议在viewmodle里面toast

**Comment by GuoguoDad** [comment]
> 用state定义的值设置了，是不会清除的，怎么在viewmodle里面显示toast呢

不建议在viewmodle里面toast

**Comment by wppcc** [comment]
viewmodel里面有些时候会处理下业务逻辑，可能会有提示
