### ISSUE TITLE
HomeFragment中addView(adView)未生效

### ISSUE THREAD

**Issue by heluicare** [liuaries/android_mall#3]
版本：clone下来master运行和直接下载的Release v1.2.2中的mall_release.apk
描述：HomeFragment中addView(adView)未生效，即首页没有adView
        `binding.collapsableContent.run {`
            `removeAllViews()`
            `addView(banner)`
            `addView(adView)`   //这一行没有生效，即跑起来之后首页没有adView
            `addView(nineMenuView)`
        `}`

**Comment by GuoguoDad** [comment]
> 版本：clone下来master运行和直接下载的Release v1.2.2中的mall_release.apk 描述：HomeFragment中addView(adView)未生效，即首页没有adView `binding.collapsableContent.run {` `removeAllViews()` `addView(banner)` `addView(adView)` //这一行没有生效，即跑起来之后首页没有adView `addView(nineMenuView)` `}`

什么机型，手上Android模拟器、华为meta10鸿蒙2.+ 正常

**Comment by heluicare** [comment]
首先感谢作者抽空回复~

这边试过了几个测试机华为Meta10 Pro（EMUI 10.0.0、Android 10）、华为P10（EMUI 8.0.0 Android 8）、vivo X23（Funtouch OS_10 Android 9）结果都是一样，不显示adView。

另外把 home_ad.xml 修改如下

```
<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="300dp"
    android:background="@color/colorAccent"
    android:layout_height="100dp">

    <ImageView
        android:id="@+id/adImg"
        android:background="@color/purple_200"
        android:layout_width="150dp"
        android:layout_height="100dp"
        android:scaleType="fitXY" />

</RelativeLayout>

```

把 HomeFragment 修改如下

```
binding.collapsableContent.run {
            removeAllViews()
            addView(banner)
            adView.layoutParams = LayoutParams(LayoutParams.MATCH_PARENT, 300)
            addView(adView)
            addView(nineMenuView)
        }
```

adView也没有显示出相应的背景色，只有一个高度为300的空白区域。

而如果修改如下：

```
binding.collapsableContent.run {
            removeAllViews()
            addView(banner)
            adView.layoutParams = LayoutParams(LayoutParams.MATCH_PARENT, 300)
            adView.setBackgroundResource(R.color.indicator_selected_color)
            addView(adView)
            addView(nineMenuView)
        }
```

页面上则有一个高度为300的绿色区域。

还有如果修改如下：

```
binding.collapsableContent.run {
            removeAllViews()
            addView(banner)
            var img: ImageView = ImageView(context)
            img.setImageResource(R.drawable.default_img)
            addView(img)
            addView(nineMenuView)
        }
```

此时页面可以显示img

所以貌似是通过添加布局文件的方式然后不知什么原因导致adView的Measure失效了？

**Comment by GuoguoDad** [comment]
> 首先感谢作者抽空回复~
> 
> 
> 
> 这边试过了几个测试机华为Meta10 Pro（EMUI 10.0.0、Android 10）、华为P10（EMUI 8.0.0 Android 8）、vivo X23（Funtouch OS_10 Android 9）结果都是一样，不显示adView。
> 
> 
> 
> 另外把 home_ad.xml 修改如下
> 
> 
> 
> ```
> 
> <?xml version="1.0" encoding="utf-8"?>
> 
> <RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
> 
>     android:layout_width="300dp"
> 
>     android:background="@color/colorAccent"
> 
>     android:layout_height="100dp">
> 
> 
> 
>     <ImageView
> 
>         android:id="@+id/adImg"
> 
>         android:background="@color/purple_200"
> 
>         android:layout_width="150dp"
> 
>         android:layout_height="100dp"
> 
>         android:scaleType="fitXY" />
> 
> 
> 
> </RelativeLayout>
> 
> 
> 
> ```
> 
> 
> 
> 把 HomeFragment 修改如下
> 
> 
> 
> ```
> 
> binding.collapsableContent.run {
> 
>             removeAllViews()
> 
>             addView(banner)
> 
>             adView.layoutParams = LayoutParams(LayoutParams.MATCH_PARENT, 300)
> 
>             addView(adView)
> 
>             addView(nineMenuView)
> 
>         }
> 
> ```
> 
> 
> 
> adView也没有显示出相应的背景色，只有一个高度为300的空白区域。
> 
> 
> 
> 而如果修改如下：
> 
> 
> 
> ```
> 
> binding.collapsableContent.run {
> 
>             removeAllViews()
> 
>             addView(banner)
> 
>             adView.layoutParams = LayoutParams(LayoutParams.MATCH_PARENT, 300)
> 
>             adView.setBackgroundResource(R.color.indicator_selected_color)
> 
>             addView(adView)
> 
>             addView(nineMenuView)
> 
>         }
> 
> ```
> 
> 
> 
> 页面上则有一个高度为300的绿色区域。
> 
> 
> 
> 还有如果修改如下：
> 
> 
> 
> ```
> 
> binding.collapsableContent.run {
> 
>             removeAllViews()
> 
>             addView(banner)
> 
>             var img: ImageView = ImageView(context)
> 
>             img.setImageResource(R.drawable.default_img)
> 
>             addView(img)
> 
>             addView(nineMenuView)
> 
>         }
> 
> ```
> 
> 
> 
> 此时页面可以显示img
> 
> 
> 
> 所以貌似是通过添加布局文件的方式然后不知什么原因导致adView的Measure失效了？
> 
> 

已修复，改动见AdView  16行

**Comment by GuoguoDad** [comment]
@heluicare  已修复，原因少了2参数

`class AdView(context: Context): FrameLayout(context) {
    private var binding: HomeAdBinding
    private var imageLoader: ImageLoader = CoilUtil.getImageLoader()
    init {
        **_binding = HomeAdBinding.inflate(LayoutInflater.from(context), this, true)_**
    }

    fun setData(url: String) {
        binding.adImg.load(url, imageLoader ) {
            crossfade(true)
            placeholder(R.drawable.default_img)
            error(R.drawable.default_img)
        }
    }
}`

**Comment by heluicare** [comment]
感谢作者~   

没足够仔细阅读代码 ==||
