### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by guozhiqiang123** [liuaries/android_mall#5]
建议进入页面的数据加载不要在UI层直接调用ViewModel中的方法，而是应该改为在ViewModel的构造函数中调用。
在UI层调用有个问题是，旋转屏幕等操作，会重建页面导致再次调用加载数据的方法，造成页面状态被重置，接口被多次调用的问题。

**Comment by guozhiqiang123** [comment]
在补充一点，Fragment一定要留一个空构造函数，用于恢复的时候FragmentManager通过反射初始化实例。往Fragment中传递参数不要通过构造函数，而是通过Bundle传递，这样页面被销毁重建不会丢失数据。

**Comment by GuoguoDad** [comment]
> 在补充一点，Fragment一定要留一个空构造函数，用于恢复的时候FragmentManager通过反射初始化实例。往Fragment中传递参数不要通过构造函数，而是通过Bundle传递，这样页面被销毁重建不会丢失数据。

感谢你的建议，有空修改下
