### ISSUE TITLE
React-Native模块配置问题求教

### ISSUE THREAD

**Issue by zhengjirui** [liuaries/android_mall#6]
1.源码中[hermes-engine-0.70.1-release.aar](https://github.com/GuoguoDad/jd_mall/blob/master/local_lib/hermes/hermes-engine-0.70.1-release.aar)是怎么编辑生成，对应还有一个[hermes-engine-0.70.1-release.aar](https://github.com/GuoguoDad/jd_mall/blob/master/local_lib/hermes/hermes-engine-0.70.1-release.aar)。我知道现在好像可以直接指定版本implementation("com.facebook.react:hermes-android:0.70.1")，但是我还是想知道博主怎么自己生成的想学习一下.
2.在rn的源码中有用到第三方依赖，而且这些依赖有一部分源码是原生端的，我在博主源码中看到是直接将第三方的源码copy进去的，想交流一下有没有简单的方式可以直接用implementation进行依赖，最好是能保证双端的统一性，

**Comment by zhengjirui** [comment]
3.补充一个问题，热更新的时候，本地图片资源是怎么处理的，我个人通过bsdiff和bspatch可以将包拆分且合并，但是图片资源不知道怎么处理，我看博主介绍的是这样的【4，React Native 发起 CDN 资源请求 资源请求会先询问某个 CDN 的边缘节点，如果该边缘节点没有缓存，则会去源站拉取；如果该边缘节点有缓存，则直接返回。】这个意思是直接使用http:这样的网络图片吗，还是什么技术

**Comment by GuoguoDad** [comment]
> 1.源码中[hermes-engine-0.70.1-release.aar](https://github.com/GuoguoDad/jd_mall/blob/master/local_lib/hermes/hermes-engine-0.70.1-release.aar)是怎么编辑生成，对应还有一个[hermes-engine-0.70.1-release.aar](https://github.com/GuoguoDad/jd_mall/blob/master/local_lib/hermes/hermes-engine-0.70.1-release.aar)。我知道现在好像可以直接指定版本implementation("com.facebook.react:hermes-android:0.70.1")，但是我还是想知道博主怎么自己生成的想学习一下. 2.在rn的源码中有用到第三方依赖，而且这些依赖有一部分源码是原生端的，我在博主源码中看到是直接将第三方的源码copy进去的，想交流一下有没有简单的方式可以直接用implementation进行依赖，最好是能保证双端的统一性，

1、arr 在react-native的72版本之前官方都是提供的，由于包大小原因，72版本之后官方不在提供
2、可以抽成npm库, link即可

**Comment by GuoguoDad** [comment]
> 3.补充一个问题，热更新的时候，本地图片资源是怎么处理的，我个人通过bsdiff和bspatch可以将包拆分且合并，但是图片资源不知道怎么处理，我看博主介绍的是这样的【4，React Native 发起 CDN 资源请求 资源请求会先询问某个 CDN 的边缘节点，如果该边缘节点没有缓存，则会去源站拉取；如果该边缘节点有缓存，则直接返回。】这个意思是直接使用http:这样的网络图片吗，还是什么技术

3、这里采用网络图片，也可以做成 热更，工作量较大，这里不细说
4、React Native 发起 CDN 资源请求 资源请求会先询问某个 CDN 的边缘节点，如果该边缘节点没有缓存，则会去源站拉取；如果该边缘节点有缓存，则直接返回。这里指的是远程的 jsbundle 文件
